;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-electric-semi&comma
        mouse-set-region
        subword-left
        subword-right
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        overwrite-mode
        ))
